name: Something From Nothing
favicon: null
layout_spectrum: 0.7575153
typography_spectrum: 0.9088365
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8409868
  lightness: 0.2887246
  saturation: 0.03936853
  rhythmicContrast: 0.3541858
purpose: []
